# Configuration principale
nombre_retry = 5
notification_max = 25
type_acteur = "SI"

[environnement]
api_url = ""
token_url = ""

[header]
editor_name = "SI_XYZ"
application_name = "script_HUBEE_DINUM"
software_version = "2.0.0"

[[demarches]]
demarche_nom = "CERTDC"
client_id = ""
client_secret = ""
dossier_telechargement = "./downloads/CERTDC/"
statut_minimal = "IN_PROGRESS"    # statut intermédiaire : SENT, SI_RECEIVED ou IN_PROGRESS
statut_maximal = "DONE"           # statut final : DONE ou REFUSED

[[demarches]]
demarche_nom = "EtatCivil"
client_id = ""
client_secret = ""
dossier_telechargement = "./downloads/EtatCivil/"
statut_minimal = "IN_PROGRESS"    # statut intermédiaire : SENT, SI_RECEIVED ou IN_PROGRESS
statut_maximal = "DONE"           # statut final : DONE ou REFUSED
