openapi: 3.0.0
info:
  description: This is the swagger describing API exposed by HubEE.
  version: 1.2.7
  title: Folder
x-wso2-basePath: /teledossiers/v1
x-wso2-production-endpoints: '#/x-wso2-endpoints/microservice'
x-wso2-endpoints:
  - microservice:
      urls:
        - https://microservice/teledossiers/v1
  - microserviceBinary:
      urls:
        - https://microservice/teledossiers/v1
      advanceEndpointConfig:
        timeoutInMillis: 300000
servers:
  - url: https://apirecettenhube.imfr.cgi.com/teledossiers/v1
    description: Serveur REC CGI
paths:
  /notifications:
    get:
      tags:
        - Notifications
      summary: Find notifications by recipient
      description: >-
        This method allows the retrieve of a notifications filtered by
        recipient.<br/> This method is accessible by <b>OSL</b>, <b>SI</b> and
        <b>ADMIN</b>
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
      operationId: listNotification
  /notifications/{notificationId}:
    delete:
      tags:
        - Notifications
      summary: Delete an existing notification
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
      description: >-
        This method allows the deletion of a notification by its
        identifier.<br/> This method is accessible by <b>OSL</b>, <b>SI</b> and
        <b>ADMIN</b>
      operationId: deleteNotification
  /folders:
    post:
      tags:
        - Folders
      summary: Create a new folder
      description: >-
        This method allows the creation of a folder meta-data.<br/> This method
        is accessible by <b>OSL</b> and <b>ADMIN</b>
      operationId: createFolder
      security:
        - dinum_auth:
            - OSL
            - ADMIN
  /folders/{folderId}:
    get:
      tags:
        - Folders
      summary: Find folder by Id
      operationId: getFolderById
      description: >-
        This method allows the retrieve of a folder by its identifier.<br/> This
        method is accessible by <b>OSL</b> and <b>ADMIN</b>
      security:
        - dinum_auth:
            - OSL
            - ADMIN
    patch:
      tags:
        - Folders
      summary: Update an existing folder
      description: >-
        This method allows the modification of the folder <b>status</b> and
        <b>closeDateTime</b>.<br/> This method is accessible by <b>OSL</b> and
        <b>ADMIN</b>.<br/> Update the folder status will not change cases
        status, except for the "HUBEE_COMPLETED" value at folder creation.<br/>
        <b>OSL</b> or <b>ADMIN</b> must update the cases status before the
        folder status.
      operationId: updateFolder
      security:
        - dinum_auth:
            - OSL
            - ADMIN
    post:
      tags:
        - Folders
      summary: Update an existing folder
      description: >-
        This method allows the modification of the folder <b>status</b> and
        <b>closeDateTime</b>.<br/> This method is accessible by <b>OSL</b> and
        <b>ADMIN</b>
      operationId: updateFolderWithPost
      security:
        - dinum_auth:
            - OSL
            - ADMIN
    delete:
      tags:
        - Folders
      summary: Delete an existing folder
      security:
        - dinum_auth:
            - OSL
            - ADMIN
      description: >-
        This method allows the deletion of a folder by its identifier when its
        globalStatus is <b>HUBEE_RECEIVED</b> and it has no event or
        notification.<br/> This method is accessible by <b>OSL</b> and
        <b>ADMIN</b>
      operationId: deleteFolder
  /folders/{folderId}/attachments/{attachmentId}:
    put:
      tags:
        - Folders
      summary: Upload a new folder attachment
      description: >-
        This method allows the upload of a binary file in the HUB.<br/> This
        method is accessible by <b>OSL</b> and <b>ADMIN</b>
      operationId: uploadFolderAttachment
      x-wso2-production-endpoints: '#/x-wso2-endpoints/microserviceBinary'
      security:
        - dinum_auth:
            - OSL
            - ADMIN
  /cases/migrate:
    put:
      tags:
        - Cases
      summary: Update an existing case
      description: >-
        This method migrate all cases, events and notification from an organization to an other and is only accesible from the portal
      operationId: migrateCases
      security:
        - dinum_auth:
            - SI
            - ADMIN
  /cases/{caseId}:
    get:
      tags:
        - Cases
      summary: Find case by id
      operationId: getCaseById
      description: >-
        This method allows the retrieve of a case by its identifier.<br/> This
        method is accessible by <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
    patch:
      tags:
        - Cases
      summary: Update an existing case
      description: >-
        This method allows the modification of the status of a case.<br/> This
        method is accessible by <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>.<br/>
        Update the case status must be followed by the creation of an event to
        create a notification.
      operationId: updateCase
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
    post:
      tags:
        - Cases
      summary: Update an existing case
      description: >-
        This method allows the modification of the status of a case.<br/> This
        method is accessible by <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>
      operationId: updateCaseWithPost
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
  /cases/{caseId}/attachments/{attachmentId}:
    get:
      tags:
        - Cases
      summary: Download attachment
      operationId: downloadCaseAttachmentById
      description: >-
        This method allows the download of a case binary file by its
        identifier.<br/> This method is accessible by <b>SI</b>, <b>OSL</b> and
        <b>ADMIN</b>
      security:
        - dinum_auth:
            - SI
            - OSL
            - ADMIN
  /cases/{caseId}/events:
    post:
      tags:
        - Cases
      summary: Create a new event
      description: >-
        This method allows the addition of a event in the folder.<br/> This
        method is accessible by <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>
      operationId: createEvent
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
  /cases/{caseId}/events/{eventId}:
    get:
      tags:
        - Cases
      summary: Find event by Id
      operationId: getEventById
      description: >-
        This method allows the retrieve of a event by its identifier.<br/> This
        method is accessible by <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
    patch:
      tags:
        - Cases
      summary: Update an existing event
      description: >-
        This method allows the modification of the status taken into account by
        the recipient of the event.<br/> This method is accessible by
        <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>
      operationId: updateEvent
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
    post:
      tags:
        - Cases
      summary: Update an existing event
      description: >-
        This method allows the modification of the status taken into account by
        the recipient of the event.<br/> This method is accessible by
        <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>
      operationId: updateEventWithPost
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
    delete:
      tags:
        - Cases
      summary: Delete an existing event
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
      description: >-
        This method allows the deletion of an event by its identifier, if the
        action type is <b>ATTACH_DEPOSIT</b> and the status is
        <b>IN_PROGRESS</b>.<br/> This method is accessible by <b>OSL</b>,
        <b>SI</b> and <b>ADMIN</b>
      operationId: deleteEvent
  /cases/{caseId}/events/{eventId}/attachments/{attachmentId}:
    put:
      tags:
        - Cases
      summary: Upload a new event attachment
      description: >-
        This method allows the upload of a binary file in the event of a
        case.<br/> This method is accessible by <b>OSL</b>, <b>SI</b> and
        <b>ADMIN</b>
      operationId: uploadEventAttachment
      x-wso2-production-endpoints: '#/x-wso2-endpoints/microserviceBinary'
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
    get:
      tags:
        - Cases
      summary: Download attachment
      operationId: downloadEventAttachmentById
      description: >-
        This method allows the download of a binary file of a event by its
        identifier.<br/> This method is accessible by <b>OSL</b>, <b>SI</b> and
        <b>ADMIN</b>
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
  /attachmentsIdsForPurge:
    get:
      tags:
        - Cases
      summary: Find couple folder_attachment_id/case_id for binary purge in portal
      description: >-
        This method allows the retrieve of a list of id of case filtered by
        status and if binary are not already delete.<br/> This method is accessible by <b>OSL</b>, <b>SI</b> and
        <b>ADMIN</b>
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
      operationId: getListIdCaseForPurge
  /idsPurged:
    put:
      tags:
        - Cases
      summary: Update column portal_purge
      description: >-
        This method permit to update column purge_portal in case_attachment table for a list of folder_attachment_id.<br/>
        This method is accessible by <b>OSL</b>, <b>SI</b> and <b>ADMIN</b>
      security:
        - dinum_auth:
            - OSL
            - SI
            - ADMIN
      operationId: updateCaseAttachmentPortalBinary
components:
  securitySchemes:
    dinum_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: /token
          scopes:
            OSL: osl
            SI: si
            ADMIN: admin